'use client';

import { ThumbsUp, AlertCircle, Sparkles } from 'lucide-react';

interface ReviewSynthesisProps {
  synthesis: {
    loves: string[];
    considers: string[];
  } | null;
}

export default function ReviewSynthesis({ synthesis }: ReviewSynthesisProps) {
  if (!synthesis) return null;

  return (
    <div className="bg-[var(--color-paper-sunken)] p-10 lg:p-16">
      <div className="max-w-4xl mx-auto">
        <div className="flex items-center gap-3 mb-12">
          <Sparkles size={20} className="text-[var(--color-bronze)]" />
          <h2 className="text-xs uppercase tracking-[0.2em] font-bold">Customer Intelligence</h2>
        </div>

        <div className="grid md:grid-cols-2 gap-16 lg:gap-24">
          {/* Loves */}
          <div>
            <div className="flex items-center gap-3 mb-8">
              <ThumbsUp size={18} className="text-green-600" />
              <h3 className="text-lg font-display italic">What customers love</h3>
            </div>
            <ul className="space-y-6">
              {synthesis.loves.map((item, i) => (
                <li key={i} className="flex gap-4">
                  <span className="text-[var(--color-bronze)] font-mono text-xs mt-1">0{i + 1}.</span>
                  <p className="text-sm leading-relaxed text-[var(--color-ink-soft)]">{item}</p>
                </li>
              ))}
            </ul>
          </div>

          {/* Considers */}
          <div>
            <div className="flex items-center gap-3 mb-8">
              <AlertCircle size={18} className="text-[var(--color-bronze)]" />
              <h3 className="text-lg font-display italic">Things to consider</h3>
            </div>
            <ul className="space-y-6">
              {synthesis.considers.map((item, i) => (
                <li key={i} className="flex gap-4">
                  <span className="text-[var(--color-ink-quiet)] font-mono text-xs mt-1">0{i + 1}.</span>
                  <p className="text-sm leading-relaxed text-[var(--color-ink-soft)]">{item}</p>
                </li>
              ))}
            </ul>
          </div>
        </div>

        <div className="mt-16 pt-12 border-t border-[var(--color-ink-rule)] text-center">
           <p className="text-[10px] text-[var(--color-ink-muted)] italic">
             This summary is generated by AI from 24 verified purchase reviews.
           </p>
        </div>
      </div>
    </div>
  );
}
